from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import shared_memory
from sensitive_scan import sanitized_payload


ENTRY_ID_MAX_LENGTH = 96
ENTRY_ID_HASH_LENGTH = 10
COMPONENT_HASH_LENGTH = 8


def write_from_route_plan(
    project_root: Path,
    route_plan: dict[str, Any],
    *,
    task_id: str = "workspace-memory",
    summary: str = "",
    confirm: bool = False,
) -> dict[str, Any]:
    entries = planned_entries(route_plan, task_id=task_id, summary=summary)
    if not confirm:
        return {"ok": True, "dry_run": True, "entries": entries}
    written = []
    for entry in entries:
        written.append(write_entry(project_root, entry))
    index = shared_memory.rebuild_index(project_root)
    validation = shared_memory.validate_shared(project_root)
    return {"ok": validation["ok"], "dry_run": False, "entries": written, "index": index, "validation": validation}


def planned_entries(route_plan: dict[str, Any], *, task_id: str, summary: str = "") -> list[dict[str, Any]]:
    memory_plan = route_plan.get("memory_plan") if isinstance(route_plan.get("memory_plan"), dict) else {}
    entries: list[dict[str, Any]] = []
    workspace_summary = memory_plan.get("workspace_summary") if isinstance(memory_plan.get("workspace_summary"), dict) else {}
    if workspace_summary:
        entries.append(
            entry_payload(
                kind="route",
                scope="workspace",
                project_id="workspace",
                domain=str(route_plan.get("mode") or "workspace"),
                title=f"Workspace route summary for {route_plan.get('task_id') or task_id}",
                source=f"task:{task_id}",
                body=workspace_body(route_plan, summary),
                shared_memory_allowed=bool(workspace_summary.get("shared_memory_allowed")),
            )
        )
    for binding in memory_plan.get("project_summaries") if isinstance(memory_plan.get("project_summaries"), list) else []:
        if not isinstance(binding, dict):
            continue
        project_id = str(binding.get("project_id") or "project")
        route = route_for_project(route_plan, project_id)
        entries.append(
            entry_payload(
                kind="fact",
                scope="project",
                project_id=project_id,
                domain=str(route.get("domain") or binding.get("semantic_scope") or "project"),
                title=f"Project route fact for {project_id}",
                source=f"task:{task_id}",
                body=project_body(route_plan, route, binding),
                shared_memory_allowed=bool(binding.get("shared_memory_allowed", True)),
            )
        )
    return [sanitized_payload(entry, context="workspace_memory_entry") for entry in entries]


def write_entry(project_root: Path, entry: dict[str, Any]) -> dict[str, Any]:
    if not entry.get("shared_memory_allowed"):
        return {**entry, "written": False, "reason": "shared_memory_allowed is false"}
    root = shared_memory.ensure_shared_layout(project_root)
    folder = "routes" if entry["kind"] == "route" else "facts"
    path = root / folder / f"{entry['id']}.md"
    if path.exists():
        return {**entry, "written": False, "path": str(path), "reason": "entry already exists"}
    path.write_text(render_markdown(entry), encoding="utf-8")
    return {**entry, "written": True, "path": str(path)}


def entry_payload(
    *,
    kind: str,
    scope: str,
    project_id: str,
    domain: str,
    title: str,
    source: str,
    body: str,
    shared_memory_allowed: bool,
) -> dict[str, Any]:
    task_component = entry_id_source_component(source)
    entry_id = workspace_entry_id(
        task_component=task_component,
        kind=kind,
        project_id=project_id,
        domain=domain,
    )
    return {
        "id": entry_id,
        "kind": kind,
        "scope": scope,
        "project_id": project_id,
        "domain": domain,
        "status": "proposed",
        "confidence": "medium",
        "source": source,
        "supersedes": "",
        "updated_at": utc_date(),
        "title": title,
        "body": body,
        "shared_memory_allowed": shared_memory_allowed,
    }


def workspace_body(route_plan: dict[str, Any], summary: str) -> str:
    lines = [
        "## Summary",
        summary or "Workspace route plan generated by Codex Memory Harness.",
        "",
        "## Route",
        f"- Mode: `{route_plan.get('mode', '')}`",
        f"- Affected projects: `{', '.join(str(item) for item in route_plan.get('affected_projects') or [])}`",
        f"- Verification profiles: `{', '.join(str(item) for item in route_plan.get('verification_profile_ids') or [])}`",
        "",
        "## Review",
        "- Status: proposed; review before accepting as shared memory.",
    ]
    return "\n".join(lines).strip() + "\n"


def project_body(route_plan: dict[str, Any], route: dict[str, Any], binding: dict[str, Any]) -> str:
    lines = [
        "## Project Fact",
        f"- Project: `{binding.get('project_id', '')}`",
        f"- Domain: `{route.get('domain', '')}`",
        f"- CWD: `{route.get('cwd', '')}`",
        f"- Assigned scope: `{', '.join(str(item) for item in route.get('assigned_scope') or [])}`",
        f"- Verification profiles: `{', '.join(str(item) for item in route.get('verification_profile_ids') or [])}`",
        "",
        "## Source Route",
        f"- Task: `{route_plan.get('task_id', '')}`",
        f"- Mode: `{route_plan.get('mode', '')}`",
    ]
    return "\n".join(lines).strip() + "\n"


def route_for_project(route_plan: dict[str, Any], project_id: str) -> dict[str, Any]:
    for route in route_plan.get("routes") if isinstance(route_plan.get("routes"), list) else []:
        if isinstance(route, dict) and str(route.get("project_id") or "") == project_id:
            return route
    return {}


def render_markdown(entry: dict[str, Any]) -> str:
    lines = [
        "---",
        f"id: {json.dumps(entry['id'])}",
        f"scope: {json.dumps(entry['scope'])}",
        f"project_id: {json.dumps(entry['project_id'])}",
        f"domain: {json.dumps(entry['domain'])}",
        f"status: {json.dumps(entry['status'])}",
        f"confidence: {json.dumps(entry['confidence'])}",
        f"source: {json.dumps(entry['source'])}",
        f"supersedes: {json.dumps(entry['supersedes'])}",
        f"updated_at: {json.dumps(entry['updated_at'])}",
        "---",
        "",
        f"# {entry['title']}",
        "",
        str(entry["body"]).strip(),
        "",
    ]
    return str(sanitized_payload("\n".join(lines), context="workspace_memory_markdown")).strip() + "\n"


def workspace_entry_id(*, task_component: str, kind: str, project_id: str, domain: str) -> str:
    date_component = utc_date()
    task_slug = bounded_component(task_component, fallback="task", max_length=48)
    identity_parts = [
        bounded_component(kind, fallback="entry", max_length=12),
        bounded_component(project_id, fallback="project", max_length=24),
        bounded_component(domain, fallback="domain", max_length=20),
    ]
    identity_suffix = "-".join(identity_parts)
    digest = hashlib.sha256(
        "\0".join([date_component, task_slug, identity_suffix]).encode("utf-8")
    ).hexdigest()[:ENTRY_ID_HASH_LENGTH]
    suffix = f"{identity_suffix}-{digest}"
    prefix = safe_slug(f"{date_component}-{task_slug}", fallback=f"{date_component}-task")
    prefix_budget = ENTRY_ID_MAX_LENGTH - len(suffix) - 1
    if prefix_budget > 0:
        prefix = truncate_slug(prefix, prefix_budget)
        return safe_entry_id(f"{prefix}-{suffix}")
    return safe_entry_id(suffix)


def safe_entry_id(value: str) -> str:
    return truncate_slug(
        safe_slug(value, fallback=f"workspace-memory-{utc_date()}"),
        ENTRY_ID_MAX_LENGTH,
    )


def bounded_component(value: str, *, fallback: str, max_length: int) -> str:
    slug = safe_slug(value, fallback=fallback)
    if len(slug) <= max_length:
        return slug
    digest = hashlib.sha256(slug.encode("utf-8")).hexdigest()[:COMPONENT_HASH_LENGTH]
    keep = max_length - len(digest) - 1
    if keep <= 0:
        return digest[:max_length]
    return f"{truncate_slug(slug, keep)}-{digest}"


def safe_slug(value: str, *, fallback: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip().lower()).strip("-._")
    return slug or fallback


def truncate_slug(value: str, max_length: int) -> str:
    if len(value) <= max_length:
        return value
    return value[:max_length].strip("-._")


def entry_id_source_component(source: str) -> str:
    value = source.split("task:", 1)[1] if source.startswith("task:") else source
    return str(sanitized_payload(value, context="workspace_memory_entry_id"))


def utc_date() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def main() -> int:
    parser = argparse.ArgumentParser(description="Write workspace route memory into .codex/shared drafts.")
    parser.add_argument("--project-root", default=os.environ.get("CODEX_MEMORY_CWD") or os.getcwd())
    parser.add_argument("--route-file", required=True)
    parser.add_argument("--task-id", default="workspace-memory")
    parser.add_argument("--summary", default="")
    parser.add_argument("--confirm", action="store_true")
    args = parser.parse_args()
    route_plan = json.loads(Path(args.route_file).read_text(encoding="utf-8"))
    result = write_from_route_plan(Path(args.project_root).resolve(), route_plan, task_id=args.task_id, summary=args.summary, confirm=args.confirm)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result.get("ok", True) else 1


if __name__ == "__main__":
    raise SystemExit(main())
